---
- name: Create pods using deployment
  hosts: rhel-master
  become: true
  user: ansible

  tasks:
  - name: create a deployment
    command: kubectl apply -f devops-pod-deploy.yml

  - name: update deployment with new pods if image updated in docker hub
    command: kubectl rollout restart deployment.v1.apps/simple-devops-deployment
